name: attayairaq
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  geolocator: ^5.3.1
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.0+9
  cloud_firestore: 0.13.2+1
  shared_preferences: ^0.5.6+3
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.27
  flutter_spinkit: ^4.1.2+1
  uuid: ^2.0.4
  url_launcher: ^5.4.5
  provider: ^4.0.5+1
  bot_toast: ^3.0.0

   



dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:
  lint: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/

   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
        - asset: assets/fonts/Changa-Bold.ttf
          weight: 700
#        - asset: assets/fonts/Changa-Medium.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
